[package]
name = "lttws"
version = "0.1.0"
edition = "2021"

[dependencies]
lttcore = { path = "../../lttcore" }
lttnetworking = { path = "../lttnetworking" }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "*"
bincode = "1.3.3"
anyhow = "1.0"
