[package]
name = "ltti"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33.3"
lttcore = { path = "../lttcore" }
tic_tac_toe = { path = "../games/tic_tac_toe" }
crossterm = "0.20"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
