[package]
name = "lttstadium"
version = "0.1.0"
edition = "2021"

[lib]
name = "lttstadium"
path = "src/lib.rs"

[[bin]]
name = "stadium"
path = "src/bin.rs"

[dependencies]
lttcore = { path = "../lttcore" }
derive_builder = "0.10.2"
rayon = "1.5.1"
